services:
  - type: web
    name: bhratritya-foundation
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: FASTAPI_INTERNAL_URL
        value: http://127.0.0.1:8000
      - key: INTERNAL_API_URL
        value: http://127.0.0.1:8000
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
