from typing import List, Dict, Any
from pydantic import BaseModel


class PermissionDefinition(BaseModel):
    module: str
    action: str
    code: str
    description: str
    name_en: str
    name_bn: str


SYSTEM_MODULES = [
    "Dashboard",
    "Members",
    "Member Requests",
    "Groups",
    "Funds",
    "Donors",
    "Fund Collection",
    "Financial Support",
    "Beneficiaries",
    "Loans",
    "Reports",
    "Users",
    "Roles & Permissions",
    "Settings",
    "Audit Logs",
]

# Canonical Permission Registry
PERMISSION_REGISTRY: List[PermissionDefinition] = [
    # Dashboard
    PermissionDefinition(
        module="Dashboard",
        action="View",
        code="dashboard:view",
        description="View system dashboard and KPIs",
        name_en="View Dashboard",
        name_bn="ড্যাশবোর্ড দেখা",
    ),
    # Members
    PermissionDefinition(
        module="Members",
        action="View",
        code="members:view",
        description="View member profiles and lists",
        name_en="View Members",
        name_bn="সদস্য তালিকা দেখা",
    ),
    PermissionDefinition(
        module="Members",
        action="Add",
        code="members:add",
        description="Register and create new members",
        name_en="Add Members",
        name_bn="নতুন সদস্য তৈরি",
    ),
    PermissionDefinition(
        module="Members",
        action="Edit",
        code="members:edit",
        description="Edit member demographics and status",
        name_en="Edit Members",
        name_bn="সদস্য তথ্য সম্পাদনা",
    ),
    PermissionDefinition(
        module="Members",
        action="Delete",
        code="members:delete",
        description="Soft delete / archive members",
        name_en="Delete Members",
        name_bn="সদস্য নিষ্ক্রিয় বা মুছুন",
    ),
    PermissionDefinition(
        module="Members",
        action="Manage",
        code="members:manage",
        description="Full administrative access to member records",
        name_en="Manage Members",
        name_bn="সদস্য ব্যবস্থাপনা",
    ),
    # Member Requests
    PermissionDefinition(
        module="Member Requests",
        action="View",
        code="member_requests:view",
        description="View public member applications",
        name_en="View Member Requests",
        name_bn="সদস্য আবেদন দেখা",
    ),
    PermissionDefinition(
        module="Member Requests",
        action="Approve",
        code="member_requests:approve",
        description="Approve and activate pending applications",
        name_en="Approve Member Requests",
        name_bn="সদস্য আবেদন অনুমোদন",
    ),
    PermissionDefinition(
        module="Member Requests",
        action="Reject",
        code="member_requests:reject",
        description="Reject pending applications with reason",
        name_en="Reject Member Requests",
        name_bn="সদস্য আবেদন প্রত্যাখ্যান",
    ),
    # Groups
    PermissionDefinition(
        module="Groups",
        action="View",
        code="groups:view",
        description="View village groups and branches",
        name_en="View Groups",
        name_bn="গ্রুপ / গ্রাম দেখা",
    ),
    PermissionDefinition(
        module="Groups",
        action="Add",
        code="groups:add",
        description="Create new village groups",
        name_en="Add Groups",
        name_bn="নতুন গ্রুপ তৈরি",
    ),
    PermissionDefinition(
        module="Groups",
        action="Edit",
        code="groups:edit",
        description="Edit group details and signup policy",
        name_en="Edit Groups",
        name_bn="গ্রুপ সম্পাদনা",
    ),
    PermissionDefinition(
        module="Groups",
        action="Manage",
        code="groups:manage",
        description="Full administrative control over groups",
        name_en="Manage Groups",
        name_bn="গ্রুপ ব্যবস্থাপনা",
    ),
    # Funds & Accounts
    PermissionDefinition(
        module="Funds",
        action="View",
        code="funds:view",
        description="View funds and financial balances",
        name_en="View Funds",
        name_bn="তহবিল দেখা",
    ),
    PermissionDefinition(
        module="Funds",
        action="Add",
        code="funds:add",
        description="Create dedicated campaign/group funds",
        name_en="Add Funds",
        name_bn="নতুন তহবিল তৈরি",
    ),
    PermissionDefinition(
        module="Funds",
        action="Edit",
        code="funds:edit",
        description="Edit fund details and allocations",
        name_en="Edit Funds",
        name_bn="তহবিল সম্পাদনা",
    ),
    # Donors & Sadaqah
    PermissionDefinition(
        module="Donors",
        action="View",
        code="donors:view",
        description="View external donors and donation records",
        name_en="View Donors & Sadaqah",
        name_bn="দাতা ও সাদাকা দেখা",
    ),
    PermissionDefinition(
        module="Donors",
        action="Add",
        code="donors:add",
        description="Register external donors",
        name_en="Add Donors",
        name_bn="নতুন দাতা তৈরি",
    ),
    PermissionDefinition(
        module="Donors",
        action="Receive Installment",
        code="donors:receive",
        description="Receive Sadaqah / donations into funds",
        name_en="Receive Sadaqah / Donations",
        name_bn="সাদাকা / দান গ্রহণ",
    ),
    PermissionDefinition(
        module="Donors",
        action="Edit",
        code="donors:edit",
        description="Edit donor profiles",
        name_en="Edit Donors",
        name_bn="দাতা সম্পাদনা",
    ),
    PermissionDefinition(
        module="Donors",
        action="Delete",
        code="donors:delete",
        description="Delete donor records",
        name_en="Delete Donors",
        name_bn="দাতা মুছুন",
    ),
    # Fund Collection / Monthly Dues
    PermissionDefinition(
        module="Fund Collection",
        action="View",
        code="fund_collection:view",
        description="View dues, campaigns, and contributions",
        name_en="View Fund Collection",
        name_bn="চাঁদা ও সংগ্রহ দেখা",
    ),
    PermissionDefinition(
        module="Fund Collection",
        action="Add",
        code="fund_collection:add",
        description="Collect monthly membership dues and campaign income",
        name_en="Collect Dues & Contributions",
        name_bn="চাঁদা ও অনুদান সংগ্রহ",
    ),
    PermissionDefinition(
        module="Fund Collection",
        action="Edit",
        code="fund_collection:edit",
        description="Edit collection records and campaign plans",
        name_en="Edit Collections",
        name_bn="সংগ্রহ তথ্য সম্পাদনা",
    ),
    # Financial Support / Financial Activities
    PermissionDefinition(
        module="Financial Support",
        action="View",
        code="financial_support:view",
        description="View financial assistance and activity disbursements",
        name_en="View Financial Support",
        name_bn="আর্থিক সহায়তা দেখা",
    ),
    PermissionDefinition(
        module="Financial Support",
        action="Add",
        code="financial_support:add",
        description="Disburse financial assistance to beneficiaries",
        name_en="Disburse Financial Support",
        name_bn="আর্থিক সহায়তা প্রদান",
    ),
    # Beneficiaries
    PermissionDefinition(
        module="Beneficiaries",
        action="View",
        code="beneficiaries:view",
        description="View beneficiary profiles",
        name_en="View Beneficiaries",
        name_bn="সুবিধাভোগী দেখা",
    ),
    PermissionDefinition(
        module="Beneficiaries",
        action="Add",
        code="beneficiaries:add",
        description="Register new beneficiaries",
        name_en="Add Beneficiaries",
        name_bn="নতুন সুবিধাভোগী তৈরি",
    ),
    PermissionDefinition(
        module="Beneficiaries",
        action="Edit",
        code="beneficiaries:edit",
        description="Edit beneficiary details",
        name_en="Edit Beneficiaries",
        name_bn="সুবিধাভোগী সম্পাদনা",
    ),
    # Loans / Qard-e-Hasana
    PermissionDefinition(
        module="Loans",
        action="View",
        code="loans:view",
        description="View Qard-e-Hasana records and installment plans",
        name_en="View Qard-e-Hasana",
        name_bn="কর্জে হাসানা দেখা",
    ),
    PermissionDefinition(
        module="Loans",
        action="Add",
        code="loans:add",
        description="Apply and create Qard-e-Hasana records",
        name_en="Create Qard-e-Hasana",
        name_bn="কর্জে হাসানা আবেদন / তৈরি",
    ),
    PermissionDefinition(
        module="Loans",
        action="Edit",
        code="loans:edit",
        description="Edit loan parameters and installment plans",
        name_en="Edit Qard-e-Hasana",
        name_bn="কর্জে হাসানা সম্পাদনা",
    ),
    PermissionDefinition(
        module="Loans",
        action="Manage",
        code="loans:manage",
        description="Collect loan repayments and manage balances",
        name_en="Manage Qard-e-Hasana Repayments",
        name_bn="কর্জ পরিশোধ গ্রহণ ও ব্যবস্থাপনা",
    ),
    PermissionDefinition(
        module="Loans",
        action="Approve",
        code="loans:approve",
        description="Approve and disburse Qard-e-Hasana funds",
        name_en="Approve Qard-e-Hasana",
        name_bn="কর্জে হাসানা অনুমোদন",
    ),
    # Reports
    PermissionDefinition(
        module="Reports",
        action="View",
        code="reports:view",
        description="View financial summaries and analytics",
        name_en="View Reports",
        name_bn="প্রতিবেদন দেখা",
    ),
    PermissionDefinition(
        module="Reports",
        action="Export",
        code="reports:export",
        description="Export financial data to CSV / Excel",
        name_en="Export Reports",
        name_bn="প্রতিবেদন এক্সপোর্ট",
    ),
    # Users
    PermissionDefinition(
        module="Users",
        action="View",
        code="users:view",
        description="View system user accounts",
        name_en="View Users",
        name_bn="ব্যবহারকারী দেখা",
    ),
    PermissionDefinition(
        module="Users",
        action="Add",
        code="users:add",
        description="Create new user accounts",
        name_en="Add Users",
        name_bn="নতুন ব্যবহারকারী তৈরি",
    ),
    PermissionDefinition(
        module="Users",
        action="Edit",
        code="users:edit",
        description="Edit user profiles and credentials",
        name_en="Edit Users",
        name_bn="ব্যবহারকারী সম্পাদনা",
    ),
    PermissionDefinition(
        module="Users",
        action="Delete",
        code="users:delete",
        description="Deactivate system users",
        name_en="Deactivate Users",
        name_bn="ব্যবহারকারী নিষ্ক্রিয়করণ",
    ),
    # Roles & Permissions
    PermissionDefinition(
        module="Roles & Permissions",
        action="View",
        code="roles:view",
        description="View system roles and permission matrices",
        name_en="View Roles & Permissions",
        name_bn="রোল ও পারমিশন দেখা",
    ),
    PermissionDefinition(
        module="Roles & Permissions",
        action="Add",
        code="roles:add",
        description="Create custom organizational roles",
        name_en="Add Roles",
        name_bn="নতুন রোল তৈরি",
    ),
    PermissionDefinition(
        module="Roles & Permissions",
        action="Edit",
        code="roles:edit",
        description="Edit roles and assign permissions",
        name_en="Edit Roles",
        name_bn="রোল ও পারমিশন পরিবর্তন",
    ),
    PermissionDefinition(
        module="Roles & Permissions",
        action="Delete",
        code="roles:delete",
        description="Delete custom roles",
        name_en="Delete Roles",
        name_bn="রোল মুছুন",
    ),
    PermissionDefinition(
        module="Roles & Permissions",
        action="Manage",
        code="roles:manage",
        description="Full administrative power over RBAC matrix",
        name_en="Manage RBAC",
        name_bn="সম্পূর্ণ রোল ব্যবস্থাপনা",
    ),
    # Settings
    PermissionDefinition(
        module="Settings",
        action="View",
        code="settings:view",
        description="View organization profile and system configurations",
        name_en="View Settings",
        name_bn="সেটিংস দেখা",
    ),
    PermissionDefinition(
        module="Settings",
        action="Manage",
        code="settings:manage",
        description="Modify monthly fee, currency, and organization profile",
        name_en="Manage Settings",
        name_bn="সেটিংস পরিবর্তন ও ব্যবস্থাপনা",
    ),
    # Audit Logs
    PermissionDefinition(
        module="Audit Logs",
        action="View",
        code="audit_logs:view",
        description="View immutable security and transaction audit logs",
        name_en="View Audit Logs",
        name_bn="অডিট লগ দেখা",
    ),
]
