"""initial_schema_members_auth

Revision ID: 7c320c43813d
Revises: 
Create Date: 2026-08-14 09:29:12.064630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c320c43813d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Foundation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=100), nullable=True),
    sa.Column('updatedBy', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Permission',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module', 'action', name='uq_permission_module_action')
    )
    op.create_table('Role',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Role_name'), 'Role', ['name'], unique=True)
    op.create_table('Group',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('foundationId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('shortName', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('isFoundationGroup', sa.Boolean(), nullable=False),
    sa.Column('memberSignupEnabled', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=100), nullable=True),
    sa.Column('updatedBy', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['foundationId'], ['Foundation.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Group_code'), 'Group', ['code'], unique=True)
    op.create_table('RolePermission',
    sa.Column('roleId', sa.String(length=36), nullable=False),
    sa.Column('permissionId', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permissionId'], ['Permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roleId'], ['Role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('roleId', 'permissionId')
    )
    op.create_table('User',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('roleId', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('lastLogin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roleId'], ['Role.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    op.create_table('AuditLog',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('referenceId', sa.String(length=100), nullable=True),
    sa.Column('oldValue', sa.Text(), nullable=True),
    sa.Column('newValue', sa.Text(), nullable=True),
    sa.Column('ipAddress', sa.String(length=100), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_AuditLog_userId'), 'AuditLog', ['userId'], unique=False)
    op.create_table('Member',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=50), nullable=False),
    sa.Column('groupId', sa.String(length=36), nullable=False),
    sa.Column('fullName', sa.String(length=255), nullable=True),
    sa.Column('fatherName', sa.String(length=255), nullable=True),
    sa.Column('motherName', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('dob', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nationalId', sa.String(length=100), nullable=True),
    sa.Column('idDocumentType', sa.String(length=50), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('monthlyIncome', sa.Integer(), nullable=True),
    sa.Column('bloodGroup', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('altMobile', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('presentAddress', sa.Text(), nullable=True),
    sa.Column('permanentAddress', sa.Text(), nullable=True),
    sa.Column('emergencyContactName', sa.String(length=255), nullable=True),
    sa.Column('emergencyContactMobile', sa.String(length=50), nullable=True),
    sa.Column('emergencyContactRelation', sa.String(length=100), nullable=True),
    sa.Column('joinDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('maritalStatus', sa.String(length=50), nullable=True),
    sa.Column('education', sa.String(length=100), nullable=True),
    sa.Column('workplace', sa.String(length=255), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('reasonForJoining', sa.Text(), nullable=True),
    sa.Column('participation', sa.Text(), nullable=True),
    sa.Column('declarationAccepted', sa.Boolean(), nullable=False),
    sa.Column('memberType', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=100), nullable=True),
    sa.Column('updatedBy', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['groupId'], ['Group.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Member_email'), 'Member', ['email'], unique=False)
    op.create_index(op.f('ix_Member_groupId'), 'Member', ['groupId'], unique=False)
    op.create_index(op.f('ix_Member_memberId'), 'Member', ['memberId'], unique=True)
    op.create_index(op.f('ix_Member_mobile'), 'Member', ['mobile'], unique=False)
    op.create_index(op.f('ix_Member_nationalId'), 'Member', ['nationalId'], unique=False)
    op.create_index(op.f('ix_Member_status'), 'Member', ['status'], unique=False)
    op.create_table('MemberRequest',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('applicationNumber', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('fullName', sa.String(length=255), nullable=False),
    sa.Column('fatherName', sa.String(length=255), nullable=True),
    sa.Column('motherName', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('dob', sa.String(length=50), nullable=True),
    sa.Column('nationalId', sa.String(length=100), nullable=True),
    sa.Column('idDocumentType', sa.String(length=50), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('monthlyIncome', sa.Integer(), nullable=True),
    sa.Column('bloodGroup', sa.String(length=20), nullable=True),
    sa.Column('education', sa.String(length=100), nullable=True),
    sa.Column('maritalStatus', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('altMobile', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('presentAddress', sa.Text(), nullable=True),
    sa.Column('permanentAddress', sa.Text(), nullable=True),
    sa.Column('emergencyContactName', sa.String(length=255), nullable=True),
    sa.Column('emergencyContactMobile', sa.String(length=50), nullable=True),
    sa.Column('emergencyContactRelation', sa.String(length=100), nullable=True),
    sa.Column('referenceName', sa.String(length=255), nullable=True),
    sa.Column('referenceMobile', sa.String(length=50), nullable=True),
    sa.Column('referenceRelation', sa.String(length=100), nullable=True),
    sa.Column('groupId', sa.String(length=36), nullable=True),
    sa.Column('reasonForJoining', sa.Text(), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('rejectionReason', sa.Text(), nullable=True),
    sa.Column('adminMessage', sa.Text(), nullable=True),
    sa.Column('approvedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approvedBy', sa.String(length=100), nullable=True),
    sa.Column('createdMemberId', sa.String(length=36), nullable=True),
    sa.Column('submittedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['groupId'], ['Group.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MemberRequest_applicationNumber'), 'MemberRequest', ['applicationNumber'], unique=True)
    op.create_index(op.f('ix_MemberRequest_groupId'), 'MemberRequest', ['groupId'], unique=False)
    op.create_index(op.f('ix_MemberRequest_status'), 'MemberRequest', ['status'], unique=False)
    op.create_table('UserPermission',
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('permissionId', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permissionId'], ['Permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId', 'permissionId')
    )
    op.create_table('UserSession',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('jti', sa.String(length=100), nullable=False),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('ipAddress', sa.String(length=100), nullable=True),
    sa.Column('lastActive', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserSession_jti'), 'UserSession', ['jti'], unique=True)
    op.create_index(op.f('ix_UserSession_userId'), 'UserSession', ['userId'], unique=False)
    op.create_table('Document',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('documentNumber', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('cloudinaryPublicId', sa.String(length=255), nullable=True),
    sa.Column('secureUrl', sa.Text(), nullable=True),
    sa.Column('originalFilename', sa.String(length=255), nullable=True),
    sa.Column('mimeType', sa.String(length=100), nullable=True),
    sa.Column('sizeBytes', sa.Integer(), nullable=False),
    sa.Column('targetType', sa.String(length=50), nullable=False),
    sa.Column('foundationId', sa.String(length=36), nullable=True),
    sa.Column('groupId', sa.String(length=36), nullable=True),
    sa.Column('memberId', sa.String(length=36), nullable=True),
    sa.Column('categoryId', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=100), nullable=True),
    sa.Column('updatedBy', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['memberId'], ['Member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Document_documentNumber'), 'Document', ['documentNumber'], unique=True)
    op.create_index(op.f('ix_Document_memberId'), 'Document', ['memberId'], unique=False)
    op.create_table('MemberStatusHistory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('fromStatus', sa.String(length=50), nullable=False),
    sa.Column('toStatus', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changedBy', sa.String(length=100), nullable=True),
    sa.Column('changedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['memberId'], ['Member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_MemberStatusHistory_memberId'), 'MemberStatusHistory', ['memberId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_MemberStatusHistory_memberId'), table_name='MemberStatusHistory')
    op.drop_table('MemberStatusHistory')
    op.drop_index(op.f('ix_Document_memberId'), table_name='Document')
    op.drop_index(op.f('ix_Document_documentNumber'), table_name='Document')
    op.drop_table('Document')
    op.drop_index(op.f('ix_UserSession_userId'), table_name='UserSession')
    op.drop_index(op.f('ix_UserSession_jti'), table_name='UserSession')
    op.drop_table('UserSession')
    op.drop_table('UserPermission')
    op.drop_index(op.f('ix_MemberRequest_status'), table_name='MemberRequest')
    op.drop_index(op.f('ix_MemberRequest_groupId'), table_name='MemberRequest')
    op.drop_index(op.f('ix_MemberRequest_applicationNumber'), table_name='MemberRequest')
    op.drop_table('MemberRequest')
    op.drop_index(op.f('ix_Member_status'), table_name='Member')
    op.drop_index(op.f('ix_Member_nationalId'), table_name='Member')
    op.drop_index(op.f('ix_Member_mobile'), table_name='Member')
    op.drop_index(op.f('ix_Member_memberId'), table_name='Member')
    op.drop_index(op.f('ix_Member_groupId'), table_name='Member')
    op.drop_index(op.f('ix_Member_email'), table_name='Member')
    op.drop_table('Member')
    op.drop_index(op.f('ix_AuditLog_userId'), table_name='AuditLog')
    op.drop_table('AuditLog')
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_table('RolePermission')
    op.drop_index(op.f('ix_Group_code'), table_name='Group')
    op.drop_table('Group')
    op.drop_index(op.f('ix_Role_name'), table_name='Role')
    op.drop_table('Role')
    op.drop_table('Permission')
    op.drop_table('Foundation')
    # ### end Alembic commands ###
