"""add_settings_dues_campaign_beneficiary

Revision ID: ab1d1789902d
Revises: f1a2120e5758
Create Date: 2026-08-14 09:36:51.164625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1d1789902d'
down_revision: Union[str, None] = 'f1a2120e5758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Campaign',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaignId', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('targetAmount', sa.Integer(), nullable=True),
    sa.Column('startDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=100), nullable=True),
    sa.Column('updatedBy', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Campaign_campaignId'), 'Campaign', ['campaignId'], unique=True)
    op.create_table('Settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=100), nullable=True),
    sa.Column('updatedBy', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Settings_key'), 'Settings', ['key'], unique=True)
    op.create_table('Beneficiary',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('beneficiaryId', sa.String(length=50), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=True),
    sa.Column('fullName', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('presentAddress', sa.Text(), nullable=True),
    sa.Column('permanentAddress', sa.Text(), nullable=True),
    sa.Column('nationalId', sa.String(length=100), nullable=True),
    sa.Column('idDocumentType', sa.String(length=50), nullable=True),
    sa.Column('fatherOrHusbandName', sa.String(length=255), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('relationToMember', sa.String(length=100), nullable=True),
    sa.Column('assistanceType', sa.String(length=100), nullable=True),
    sa.Column('assistanceReason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=100), nullable=True),
    sa.Column('updatedBy', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['memberId'], ['Member.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Beneficiary_beneficiaryId'), 'Beneficiary', ['beneficiaryId'], unique=True)
    op.create_index(op.f('ix_Beneficiary_memberId'), 'Beneficiary', ['memberId'], unique=False)
    op.create_index(op.f('ix_Beneficiary_mobile'), 'Beneficiary', ['mobile'], unique=False)
    op.create_index(op.f('ix_Beneficiary_nationalId'), 'Beneficiary', ['nationalId'], unique=True)
    op.create_table('MonthlyContribution',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('expectedAmount', sa.Integer(), nullable=False),
    sa.Column('isAdditional', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=100), nullable=True),
    sa.Column('updatedBy', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['memberId'], ['Member.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memberId', 'month', 'year', 'isAdditional', name='uq_member_month_year_additional')
    )
    op.create_index(op.f('ix_MonthlyContribution_memberId'), 'MonthlyContribution', ['memberId'], unique=False)
    op.create_table('BeneficiaryPayment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaignId', sa.String(length=36), nullable=False),
    sa.Column('beneficiaryId', sa.String(length=36), nullable=False),
    sa.Column('ledgerTransactionId', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('referenceNumber', sa.String(length=100), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=100), nullable=True),
    sa.Column('updatedBy', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['beneficiaryId'], ['Beneficiary.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['campaignId'], ['Campaign.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ledgerTransactionId'], ['LedgerTransaction.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_BeneficiaryPayment_beneficiaryId'), 'BeneficiaryPayment', ['beneficiaryId'], unique=False)
    op.create_index(op.f('ix_BeneficiaryPayment_campaignId'), 'BeneficiaryPayment', ['campaignId'], unique=False)
    op.create_index(op.f('ix_BeneficiaryPayment_ledgerTransactionId'), 'BeneficiaryPayment', ['ledgerTransactionId'], unique=True)
    op.create_table('CampaignContribution',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaignId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=True),
    sa.Column('donorId', sa.String(length=36), nullable=True),
    sa.Column('ledgerTransactionId', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=100), nullable=True),
    sa.Column('updatedBy', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['campaignId'], ['Campaign.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['donorId'], ['Donor.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ledgerTransactionId'], ['LedgerTransaction.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['memberId'], ['Member.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CampaignContribution_campaignId'), 'CampaignContribution', ['campaignId'], unique=False)
    op.create_index(op.f('ix_CampaignContribution_donorId'), 'CampaignContribution', ['donorId'], unique=False)
    op.create_index(op.f('ix_CampaignContribution_ledgerTransactionId'), 'CampaignContribution', ['ledgerTransactionId'], unique=True)
    op.create_index(op.f('ix_CampaignContribution_memberId'), 'CampaignContribution', ['memberId'], unique=False)
    op.create_table('ContributionPayment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('monthlyContributionId', sa.String(length=36), nullable=False),
    sa.Column('ledgerTransactionId', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('paymentDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paymentMethod', sa.String(length=50), nullable=False),
    sa.Column('referenceNumber', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=100), nullable=True),
    sa.Column('updatedBy', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ledgerTransactionId'], ['LedgerTransaction.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['monthlyContributionId'], ['MonthlyContribution.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ContributionPayment_ledgerTransactionId'), 'ContributionPayment', ['ledgerTransactionId'], unique=True)
    op.create_index(op.f('ix_ContributionPayment_monthlyContributionId'), 'ContributionPayment', ['monthlyContributionId'], unique=False)
    op.create_index(op.f('ix_ContributionPayment_referenceNumber'), 'ContributionPayment', ['referenceNumber'], unique=False)
    op.add_column('Member', sa.Column('paidUntilMonth', sa.Integer(), nullable=True))
    op.add_column('Member', sa.Column('paidUntilYear', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Member', 'paidUntilYear')
    op.drop_column('Member', 'paidUntilMonth')
    op.drop_index(op.f('ix_ContributionPayment_referenceNumber'), table_name='ContributionPayment')
    op.drop_index(op.f('ix_ContributionPayment_monthlyContributionId'), table_name='ContributionPayment')
    op.drop_index(op.f('ix_ContributionPayment_ledgerTransactionId'), table_name='ContributionPayment')
    op.drop_table('ContributionPayment')
    op.drop_index(op.f('ix_CampaignContribution_memberId'), table_name='CampaignContribution')
    op.drop_index(op.f('ix_CampaignContribution_ledgerTransactionId'), table_name='CampaignContribution')
    op.drop_index(op.f('ix_CampaignContribution_donorId'), table_name='CampaignContribution')
    op.drop_index(op.f('ix_CampaignContribution_campaignId'), table_name='CampaignContribution')
    op.drop_table('CampaignContribution')
    op.drop_index(op.f('ix_BeneficiaryPayment_ledgerTransactionId'), table_name='BeneficiaryPayment')
    op.drop_index(op.f('ix_BeneficiaryPayment_campaignId'), table_name='BeneficiaryPayment')
    op.drop_index(op.f('ix_BeneficiaryPayment_beneficiaryId'), table_name='BeneficiaryPayment')
    op.drop_table('BeneficiaryPayment')
    op.drop_index(op.f('ix_MonthlyContribution_memberId'), table_name='MonthlyContribution')
    op.drop_table('MonthlyContribution')
    op.drop_index(op.f('ix_Beneficiary_nationalId'), table_name='Beneficiary')
    op.drop_index(op.f('ix_Beneficiary_mobile'), table_name='Beneficiary')
    op.drop_index(op.f('ix_Beneficiary_memberId'), table_name='Beneficiary')
    op.drop_index(op.f('ix_Beneficiary_beneficiaryId'), table_name='Beneficiary')
    op.drop_table('Beneficiary')
    op.drop_index(op.f('ix_Settings_key'), table_name='Settings')
    op.drop_table('Settings')
    op.drop_index(op.f('ix_Campaign_campaignId'), table_name='Campaign')
    op.drop_table('Campaign')
    # ### end Alembic commands ###
