"""add_fund_donor_ledger

Revision ID: f1a2120e5758
Revises: 7c320c43813d
Create Date: 2026-08-14 09:33:36.759562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a2120e5758'
down_revision: Union[str, None] = '7c320c43813d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Donor',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('donorId', sa.String(length=50), nullable=False),
    sa.Column('fullName', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('nationalId', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=100), nullable=True),
    sa.Column('updatedBy', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Donor_donorId'), 'Donor', ['donorId'], unique=True)
    op.create_index(op.f('ix_Donor_mobile'), 'Donor', ['mobile'], unique=True)
    op.create_index(op.f('ix_Donor_nationalId'), 'Donor', ['nationalId'], unique=True)
    op.create_table('Fund',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('groupId', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=100), nullable=True),
    sa.Column('updatedBy', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['groupId'], ['Group.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Fund_groupId'), 'Fund', ['groupId'], unique=False)
    op.create_table('LedgerTransaction',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('referenceId', sa.String(length=100), nullable=True),
    sa.Column('memberId', sa.String(length=36), nullable=True),
    sa.Column('donorId', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=100), nullable=True),
    sa.Column('updatedBy', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['donorId'], ['Donor.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['memberId'], ['Member.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_LedgerTransaction_donorId'), 'LedgerTransaction', ['donorId'], unique=False)
    op.create_index(op.f('ix_LedgerTransaction_memberId'), 'LedgerTransaction', ['memberId'], unique=False)
    op.create_index(op.f('ix_LedgerTransaction_referenceId'), 'LedgerTransaction', ['referenceId'], unique=False)
    op.create_index(op.f('ix_LedgerTransaction_type'), 'LedgerTransaction', ['type'], unique=False)
    op.create_table('LedgerEntry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transactionId', sa.String(length=36), nullable=False),
    sa.Column('fundId', sa.String(length=36), nullable=False),
    sa.Column('isCredit', sa.Boolean(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('groupId', sa.String(length=36), nullable=True),
    sa.Column('groupCode', sa.String(length=100), nullable=True),
    sa.Column('groupName', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=100), nullable=True),
    sa.Column('updatedBy', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['fundId'], ['Fund.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transactionId'], ['LedgerTransaction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_LedgerEntry_fundId'), 'LedgerEntry', ['fundId'], unique=False)
    op.create_index(op.f('ix_LedgerEntry_groupId'), 'LedgerEntry', ['groupId'], unique=False)
    op.create_index(op.f('ix_LedgerEntry_transactionId'), 'LedgerEntry', ['transactionId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_LedgerEntry_transactionId'), table_name='LedgerEntry')
    op.drop_index(op.f('ix_LedgerEntry_groupId'), table_name='LedgerEntry')
    op.drop_index(op.f('ix_LedgerEntry_fundId'), table_name='LedgerEntry')
    op.drop_table('LedgerEntry')
    op.drop_index(op.f('ix_LedgerTransaction_type'), table_name='LedgerTransaction')
    op.drop_index(op.f('ix_LedgerTransaction_referenceId'), table_name='LedgerTransaction')
    op.drop_index(op.f('ix_LedgerTransaction_memberId'), table_name='LedgerTransaction')
    op.drop_index(op.f('ix_LedgerTransaction_donorId'), table_name='LedgerTransaction')
    op.drop_table('LedgerTransaction')
    op.drop_index(op.f('ix_Fund_groupId'), table_name='Fund')
    op.drop_table('Fund')
    op.drop_index(op.f('ix_Donor_nationalId'), table_name='Donor')
    op.drop_index(op.f('ix_Donor_mobile'), table_name='Donor')
    op.drop_index(op.f('ix_Donor_donorId'), table_name='Donor')
    op.drop_table('Donor')
    # ### end Alembic commands ###
