"""add_loan_and_repayment

Revision ID: f84b9830ee30
Revises: ab1d1789902d
Create Date: 2026-08-14 09:40:05.586117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f84b9830ee30'
down_revision: Union[str, None] = 'ab1d1789902d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Loan',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loanNumber', sa.String(length=50), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=True),
    sa.Column('beneficiaryId', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('loanType', sa.String(length=50), nullable=False),
    sa.Column('businessType', sa.String(length=100), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('requestedDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disbursedDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('installmentType', sa.String(length=50), nullable=True),
    sa.Column('installmentAmount', sa.Integer(), nullable=True),
    sa.Column('totalInstallments', sa.Integer(), nullable=True),
    sa.Column('firstInstallmentDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nextDueDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totalPaidAmount', sa.Integer(), nullable=False),
    sa.Column('remainingBalance', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=100), nullable=True),
    sa.Column('updatedBy', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['beneficiaryId'], ['Beneficiary.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['memberId'], ['Member.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Loan_beneficiaryId'), 'Loan', ['beneficiaryId'], unique=False)
    op.create_index(op.f('ix_Loan_loanNumber'), 'Loan', ['loanNumber'], unique=True)
    op.create_index(op.f('ix_Loan_memberId'), 'Loan', ['memberId'], unique=False)
    op.create_table('LoanRepayment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loanId', sa.String(length=36), nullable=False),
    sa.Column('ledgerTransactionId', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('installmentNo', sa.Integer(), nullable=True),
    sa.Column('paymentMethod', sa.String(length=50), nullable=False),
    sa.Column('referenceNumber', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('collectedBy', sa.String(length=100), nullable=True),
    sa.Column('receiptUrl', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdBy', sa.String(length=100), nullable=True),
    sa.Column('updatedBy', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ledgerTransactionId'], ['LedgerTransaction.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['loanId'], ['Loan.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_LoanRepayment_ledgerTransactionId'), 'LoanRepayment', ['ledgerTransactionId'], unique=True)
    op.create_index(op.f('ix_LoanRepayment_loanId'), 'LoanRepayment', ['loanId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_LoanRepayment_loanId'), table_name='LoanRepayment')
    op.drop_index(op.f('ix_LoanRepayment_ledgerTransactionId'), table_name='LoanRepayment')
    op.drop_table('LoanRepayment')
    op.drop_index(op.f('ix_Loan_memberId'), table_name='Loan')
    op.drop_index(op.f('ix_Loan_loanNumber'), table_name='Loan')
    op.drop_index(op.f('ix_Loan_beneficiaryId'), table_name='Loan')
    op.drop_table('Loan')
    # ### end Alembic commands ###
