import uuid
import datetime
from typing import Optional, Dict, Any
import bcrypt
import jwt
from backend.app.core.config import settings


def verify_password(plain_password: str, hashed_password: str) -> bool:
    """
    Verifies a plaintext password against a bcrypt hash.
    Compatible with bcryptjs ($2a$, $2b$, $2y$) hashes generated by Next.js.
    """
    if not plain_password or not hashed_password:
        return False
    try:
        password_bytes = plain_password.encode("utf-8")
        hash_bytes = hashed_password.encode("utf-8")
        return bcrypt.checkpw(password_bytes, hash_bytes)
    except Exception:
        return False


def get_password_hash(password: str) -> str:
    """
    Hashes a password using bcrypt with standard salt work factor 10.
    """
    password_bytes = password.encode("utf-8")
    salt = bcrypt.gensalt(rounds=10)
    return bcrypt.hashpw(password_bytes, salt).decode("utf-8")


def create_access_token(
    data: Dict[str, Any],
    expires_delta: Optional[datetime.timedelta] = None,
    jti: Optional[str] = None,
) -> str:
    """
    Creates a signed JWT access token.
    """
    to_encode = data.copy()
    now = datetime.datetime.now(datetime.timezone.utc)

    if expires_delta:
        expire = now + expires_delta
    else:
        expire = now + datetime.timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES)

    session_id = jti or str(uuid.uuid4())
    to_encode.update({
        "iat": now,
        "exp": expire,
        "jti": session_id,
    })

    return jwt.encode(to_encode, settings.SECRET_KEY, algorithm=settings.ALGORITHM)


def decode_access_token(token: str) -> Optional[Dict[str, Any]]:
    """
    Decodes and validates a JWT access token.
    Returns payload dictionary or None if expired/invalid.
    """
    try:
        payload = jwt.decode(
            token,
            settings.SECRET_KEY,
            algorithms=[settings.ALGORITHM],
            options={"verify_exp": True},
        )
        return payload
    except (jwt.PyJWTError, Exception):
        return None


def parse_user_agent(ua: str) -> Dict[str, str]:
    """
    Extracts browser, OS, and device type from User-Agent string.
    Identical logic to Next.js auth helper.
    """
    browser = "Unknown Browser"
    os = "Unknown OS"
    device = "Desktop"

    if not ua:
        return {"browser": browser, "os": os, "device": device}

    if "Firefox" in ua:
        browser = "Firefox"
    elif "SamsungBrowser" in ua:
        browser = "Samsung Internet"
    elif "Opera" in ua or "OPR" in ua:
        browser = "Opera"
    elif "Edge" in ua or "Edg" in ua:
        browser = "Edge"
    elif "Chrome" in ua:
        browser = "Chrome"
    elif "Safari" in ua and "Chrome" not in ua:
        browser = "Safari"

    if "Windows" in ua:
        os = "Windows"
    elif "Mac OS" in ua:
        os = "MacOS"
    elif "Linux" in ua and "Android" not in ua:
        os = "Linux"
    elif "Android" in ua:
        os = "Android"
    elif "iOS" in ua or "iPhone" in ua or "iPad" in ua:
        os = "iOS"

    if "Mobile" in ua or "Android" in ua or "iPhone" in ua:
        device = "Mobile"
    elif "iPad" in ua or "Tablet" in ua:
        device = "Tablet"

    return {"browser": browser, "os": os, "device": device}
